DOCSP-43081: Change Streams
mongodb/docs-c pull request #37
Opened 2024-09-16 20:04 UTC by mcmorisi

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-golang/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-43081>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [ ] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-09-16 21:22 UTC, jordan-smith721 requested changes
Nice job! Just a few changes

2024-09-16 21:22 UTC, jordan-smith721 commented on source/read/change-streams.txt
> +scope of events you want to observe.
```suggestion
scope of events you want to observe:
```

2024-09-16 21:22 UTC, jordan-smith721 commented on source/read/change-streams.txt
> +- ``mongoc_collection_watch()``: To monitor changes in the collection
```suggestion
- ``mongoc_client_watch()``: Monitors all changes in the MongoDB deployment
- ``mongoc_database_watch()``: Monitors changes in all collections in the database
- ``mongoc_collection_watch()``: Monitors changes in the collection
```

2024-09-16 21:22 UTC, jordan-smith721 commented on source/read/change-streams.txt
> +aggregation stage.
S:
```suggestion
change events. Format the parameter as a list of objects, where each object represents an
aggregation stage.
```

2024-09-16 21:22 UTC, jordan-smith721 commented on source/read/change-streams.txt
> +Match Specific events Example
```suggestion
Match Specific Events Example
```

2024-09-16 21:22 UTC, jordan-smith721 commented on source/read/change-streams.txt
> +to open a change stream that only records update operations:
```suggestion
to open a change stream that records only update operations:
```

2024-09-17 18:29 UTC, jordan-smith721 approved these changes
LGTM w a small fix!

2024-09-17 18:29 UTC, jordan-smith721 commented on source/read/change-streams.txt
> +change events. Format the parameter as a list of object, where each object represents an
```suggestion
change events. Format the parameter as a list of objects, where each object represents an
```

2024-09-18 20:12 UTC, kevinAlbs approved these changes
LGTM as-is, but added a comment to consider an alternative looping.

2024-09-18 20:12 UTC, kevinAlbs commented on source/includes/read/change-streams.c
> +        while (mongoc_change_stream_next (change_stream, &doc)) {
`mongoc_change_stream_next` only returns true when a change is returned within the `maxAwaitTimeMS`. If no change was returned, and no error occurred, a later call to `mongoc_change_stream_next` can still return a change.

If the examples are intended to show the behavior of "wait (possibly forever) until there is an event or error", then I suggest looping as follows:

```c
while (true)
{
  bson_error_t error;
  if (mongoc_change_stream_next(change_stream, &doc))
  {
    char *str = bson_as_canonical_extended_json(doc, NULL);
    printf("Received change: %s\n", str);
    bson_free(str);
  }
  else if (mongoc_change_stream_error_document(change_stream, &error, NULL))
  {
    printf("Got error on change stream: %s\n", error.message);
    break;
  }
}
```

2024-09-18 20:21 UTC, merged