DOCSP-43069: Replace documents
mongodb/docs-c pull request #52
Opened 2024-09-26 15:40 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-golang/blob/master/REVIEWING.md)

JIRA - https://jira.mongodb.org/browse/DOCSP-43069
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-09-27 15:43 UTC, rustagir requested changes
a few small things

2024-09-27 15:43 UTC, rustagir commented on source/write/replace.txt
> +operation on a MongoDB collection. A replace operation performs differently
```suggestion
In this guide, you can learn how to use the {+driver-short+} to run a **replace
operation** on a MongoDB collection. A replace operation performs differently
```

2024-09-27 15:43 UTC, rustagir commented on source/write/replace.txt
> +- Collection: Specifies the collection to update.
```suggestion
- Collection: Specifies which collection to perform the replace operation on.
```

2024-09-27 15:43 UTC, rustagir commented on source/write/replace.txt
> +  the {+mdb-server+} manual.
```suggestion
- Query filter document: Specifies which collection documents to match. The function selects the first
  matching document to replace. For
  more information about query filters, see the 
  :manual:`Query Filter Documents section </core/document/#query-filter-documents>` in
  the {+mdb-server+} manual.
```

2024-09-27 15:43 UTC, rustagir commented on source/write/replace.txt
> +of a document in which the ``name`` field value is ``"Pizza Town"``:
```suggestion
The following example uses the ``mongoc_collection_replace_one()`` function to replace the fields and values
of a document in which the ``name`` field value is ``"Pizza Town"`` with a document in which the name is ...:
```

2024-09-27 15:43 UTC, rustagir commented on source/write/replace.txt
> +   a value for the ``_id`` field, it must match the ``_id`` value of the existing document.
```suggestion
   a value for the ``_id`` field, it must be identical to the ``_id`` value of the existing document.
```

2024-09-27 15:43 UTC, rustagir commented on source/write/replace.txt
> +~~~~~~~
```suggestion
Replace Options Example
~~~~~~~~~~~~~~~~~~~~~~~
```

2024-09-30 14:50 UTC, rustagir approved these changes

2024-09-30 16:50 UTC, kevinAlbs approved these changes

2024-09-30 17:26 UTC, merged