DOCSP-29036: Generate staging link
mongodb/docs-c pull request #7
Opened 2024-04-01 15:37 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-golang/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-29036>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-04-03 15:04 UTC, caitlindavey requested changes
LGTM - Few tweaks here.

2024-04-03 15:49 UTC, norareidy commented on source/libmongoc/guides/distinct-mapreduce.txt
Hm they seem to be working for me. So both the left and right toggles bring you to the visual studio guide?

2024-04-08 18:51 UTC, kevinAlbs reviewed
I grouped feedback in one comment since adding comments to files was slow. Here is feedback after skimming the stage links:

https://preview-mongodbnorareidy.gatsbyjs.io/c/DOCSP-29036-staging/libbson/
Replace link to `www.mongoc.org`? I expect the new reference docs landing page will be at a `mongodb.com` URL similar.

https://preview-mongodbnorareidy.gatsbyjs.io/c/DOCSP-29036-staging/libbson/api/bson_t/bson_append_oid/
Fix format of `:refson_t`

https://preview-mongodbnorareidy.gatsbyjs.io/c/DOCSP-29036-staging/libbson/tutorials/include-and-link/
Sample code for `hello_bson.c` does not appear to show syntax highlighting. Compare with https://mongoc.org/libbson/current/include-and-link.html. Add `:language: c` to code sample? Question applies to other `..literal-include` code samples?

https://preview-mongodbnorareidy.gatsbyjs.io/c/DOCSP-29036-staging/libmongoc/tutorials/obtaining-libraries/from-source/
- Fix formatting of `git-clone` next to `Despite the name`. 
- Suggest using inline footnotes to retain the `XCode [1]` and `Visual Studio [2]` footnote links in the original documentation: https://mongoc.org/libmongoc/1.26.2/learn/get/from-source.html#id5. https://github.com/mongodb/docs-cpp/pull/7#discussion_r1526792861 shows example use of inline footnotes.
- Remove `<cmake--install.--config>`.

https://preview-mongodbnorareidy.gatsbyjs.io/c/DOCSP-29036-staging/libmongoc/tutorials/obtaining-libraries/installing/
Remove extra backticks around `CMakeLists.txt` in code snippet caption.

https://preview-mongodbnorareidy.gatsbyjs.io/c/DOCSP-29036-staging/libmongoc/howto/source-install/
- Remove extra backticks around `pkg-config` in code snippet caption.
- Remove `<cmake--install.--config>` and `<cmake.--build>`

https://preview-mongodbnorareidy.gatsbyjs.io/c/DOCSP-29036-staging/libmongoc/guides/
Remove `Client-Side Field Level Encryption`. `Client-Side Field Level Encryption` is already nested under `In-Use Encryption`. This results in the page showing twice in the left-hand navigation.

2024-04-08 18:51 UTC, kevinAlbs commented on snooty.toml
> +    "/libbson/api",
Confirming: should the API documentation be migrated?

I expect the C team will own the API documentation. Maybe the "API Reference" sections can link to:

- https://mongoc.org/libbson/current/api.html
- https://mongoc.org/libmongoc/current/api.html

2024-04-10 16:39 UTC, kevinAlbs commented on source/libmongoc/tutorials/obtaining-libraries/installing.txt
> +  :caption: `CMakeLists.txt`
```suggestion
  :caption: CMakeLists.txt
```

2024-04-10 16:39 UTC, kevinAlbs commented on source/libmongoc/howto/source-install.txt
> +         :caption: Ask `pkg-config` what directories it will search by default
```suggestion
         :caption: Ask pkg-config what directories it will search by default
```

2024-04-10 16:39 UTC, kevinAlbs commented on snooty.toml
> +    "/libbson/api",
API docs removed. Resolving.

2024-04-10 17:13 UTC, kevinAlbs approved these changes
LGTM with backtick removals (commented in files) and this change:

https://preview-mongodbnorareidy.gatsbyjs.io/c/DOCSP-29036-staging/libmongoc/tutorials/obtaining-libraries/from-source/
Remove the `<cmake.-G>` `<cmake.-T>` and `<cmake.-A>` in the footnotes. Those were previously used by Sphinx to link to CMake documentation.

2024-04-10 19:11 UTC, merged